# Mesh Simplification

In this notebook, I wish to explore the basics of Mesh Simplification. The work in this notebook builds on the preliminary work done in [mesh-simplification.md](../mesh-simplification.md). In that file, we defined our problem statement as follows.

*"We would like to implement a mesh simplification algorithm that maintains the original coordinates and positions of our vertices, such that when they are loaded to a scene they can share the same vertex buffer"*

Current problems with simplification algorithms include the fact that they create new vertices in an attempt to maintain the original shape and minimize the overall error. We found that using the algorithm "Simplification: Quadric Edge Collapse Decimation’ in MeshLab while setting the parameter `optimalposition` to be False helped achieve our intended result. However, the order of our indicies was still not maintained.

Here, we explore the basics of the PyMeshLab API and implement our algorithm using Python while applying some data cleaning steps to maintain our vertex order in the decimated mesh.

In [1]:
import pandas as pd
import numpy as np
import pymeshlab

## Basic Implementation of Filters

We import a mesh using the `MeshSet()` class in PyMeshLab.

In [4]:
ms = pymeshlab.MeshSet()
# ms.load_new_mesh('../../../models/foot/human-foot.obj')

Now that we have the mesh in memory, we should be able to view basic attributes relating to it. Here, we see the list of vertices we have available

In [4]:
# Need to create a reference to the current mesh
m = ms.current_mesh()
v_matrix = m.vertex_matrix()

v_matrix

array([[ 0.059608,  0.383419, -0.047925],
       [-0.030599, -0.01601 , -0.020009],
       [ 0.052395,  0.402345,  0.102574],
       ...,
       [ 0.174218,  0.030867,  0.461069],
       [ 0.163158,  0.035477,  0.397872],
       [-0.056806,  0.012867,  0.570864]], shape=(800, 3))

We see the familiar (800,3) shaped array implying 800 vertices each with x,y,z coordinates. What about faces?

In [5]:
m = ms.current_mesh()
f_matrix = m.face_matrix()

f_matrix

array([[715,  31,  33],
       [715,  33, 712],
       [ 86,  16,  17],
       ...,
       [786,  95,  44],
       [647, 799,  95],
       [799, 651,  95]], shape=(1586, 3), dtype=int32)

1586 faces and 3 columns, implying that our data has been pre-converted to triangles. [We saw in earlier EDA](obj-eda.ipynb) that our original obj file had a mix of quads and triangles. It seems that loading to meshlab has automatically converted all quads to triangles.

We can even convert to dataframe.

In [6]:
vertex_df = pd.DataFrame(v_matrix, columns=["X", "Y", "Z"])
vertex_df.head()

          X         Y         Z
0  0.059608  0.383419 -0.047925
1 -0.030599 -0.016010 -0.020009
2  0.052395  0.402345  0.102574
3  0.049393 -0.015811 -0.022423
4 -0.061567  0.421855 -0.066727

In [7]:
face_df = pd.DataFrame(f_matrix, columns=["1", "2", "3"])
face_df.head()

     1    2    3
0  715   31   33
1  715   33  712
2   86   16   17
3   86   17   83
4   59  795  796

Let's apply a filter. In [mesh-decimation.md markdown file](../mesh-simplification.md) we discussed working with MeshLab through the GUI. In that document, we applied a Decimation with Quadric error, while maintaining the original mesh vertices. Let's do the same through the Python API.

In the [API](https://pymeshlab.readthedocs.io/en/latest/filter_list.html#meshing_decimation_quadric_edge_collapse) we see that this function is called as a method on our MeshSet(). Let's do this, using the default arguments, except for `optimalplacement` which we shall set to `False`. This argument controls the placement of our decimated vertices. In this case, we want our decimated vertices to maintain their original location coordinates.

In [8]:
ms.meshing_decimation_quadric_edge_collapse(optimalplacement=False)

Let's see what the result looks like. We're expecting a reduction in the number of vertices.

In [9]:
m = ms.current_mesh()
v_matrix_decimate = m.vertex_matrix()

v_matrix_decimate

array([[ 0.059608,  0.383419, -0.047925],
       [-0.030599, -0.01601 , -0.020009],
       [ 0.052395,  0.402345,  0.102574],
       ...,
       [ 0.100379, -0.002407,  0.430997],
       [ 0.130661,  0.005967,  0.426889],
       [ 0.174218,  0.030867,  0.461069]], shape=(403, 3))

Indeed we observe that our mesh has reduced vertices. Let's convert to dataframe and see what these vertices look like.

In [10]:
vertex_df_decimate = pd.DataFrame(v_matrix_decimate, columns = ["X", "Y", "Z"])
vertex_df_decimate.head()

          X         Y         Z
0  0.059608  0.383419 -0.047925
1 -0.030599 -0.016010 -0.020009
2  0.052395  0.402345  0.102574
3  0.049393 -0.015811 -0.022423
4 -0.061567  0.421855 -0.066727

In order to see whether our vertices in `vertex_df_decimate` match with the original, I will apply the following transformations.

1) Create a new column containing the tuple of (x,y,z) coordinates for each dataframe.
2) Merge dataframes based on this column (innerjoin).
3) Verfiy that the number of rows in each case is the same (i.e. no unmatched rows)

In [11]:
vertex_df['coords'] = vertex_df[["X", "Y", "Z"]].apply(tuple, axis=1)
vertex_df = vertex_df.reset_index()
vertex_df.head()

   index         X         Y         Z                            coords
0      0  0.059608  0.383419 -0.047925   (0.059608, 0.383419, -0.047925)
1      1 -0.030599 -0.016010 -0.020009  (-0.030599, -0.01601, -0.020009)
2      2  0.052395  0.402345  0.102574    (0.052395, 0.402345, 0.102574)
3      3  0.049393 -0.015811 -0.022423  (0.049393, -0.015811, -0.022423)
4      4 -0.061567  0.421855 -0.066727  (-0.061567, 0.421855, -0.066727)

In [12]:
vertex_df_decimate['coords'] = vertex_df_decimate[["X", "Y", "Z"]].apply(tuple, axis=1)
vertex_df_decimate = vertex_df_decimate.reset_index()
vertex_df_decimate.head()

   index         X         Y         Z                            coords
0      0  0.059608  0.383419 -0.047925   (0.059608, 0.383419, -0.047925)
1      1 -0.030599 -0.016010 -0.020009  (-0.030599, -0.01601, -0.020009)
2      2  0.052395  0.402345  0.102574    (0.052395, 0.402345, 0.102574)
3      3  0.049393 -0.015811 -0.022423  (0.049393, -0.015811, -0.022423)
4      4 -0.061567  0.421855 -0.066727  (-0.061567, 0.421855, -0.066727)

In [13]:
merged_df_vertex = pd.merge(vertex_df, vertex_df_decimate, how="outer", on="coords")
len(merged_df_vertex)

merged_df_vertex

,index_x,X_x,Y_x,Z_x,coords,index_y,X_y,Y_y,Z_y
0,645,-0.224832,0.030038,0.526462,"(-0.224832, 0.030038, 0.526462)",325.0,-0.224832,0.030038,0.526462
1,98,-0.223318,0.034579,0.441157,"(-0.223318, 0.034579, 0.441157)",92.0,-0.223318,0.034579,0.441157
2,299,-0.221680,0.043812,0.651764,"(-0.22168, 0.043812, 0.651764)",193.0,-0.221680,0.043812,0.651764
3,644,-0.221125,0.076088,0.533599,"(-0.221125, 0.076088, 0.533599)",324.0,-0.221125,0.076088,0.533599
4,99,-0.220750,0.085796,0.448143,"(-0.22075, 0.085796, 0.448143)",93.0,-0.220750,0.085796,0.448143
...,...,...,...,...,...,...,...,...,...
795,41,0.167509,0.009247,0.461653,"(0.167509, 0.009247, 0.461653)",38.0,0.167509,0.009247,0.461653
796,110,0.167673,0.057930,0.524913,"(0.167673, 0.05793, 0.524913)",102.0,0.167673,0.057930,0.524913
797,636,0.171731,0.034788,0.531401,"(0.171731, 0.034788, 0.531401)",317.0,0.171731,0.034788,0.531401
798,797,0.174218,0.030867,0.461069,"(0.174218, 0.030867, 0.461069)",402.0,0.174218,0.030867,0.461069
799,93,0.180927,0.052487,0.460484,"(0.180927, 0.052487, 0.460484)",87.0,0.180927,0.052487,0.460484

Perfect. We observe that each vertex in our 2 meshes are exactly aligned. To drive this point home, I shall repeat the above experiment with the same filter except this time I wont set the `optimalplacement` parameter to False. In this case, I expect that the model will create new vertices in our decimated mesh to maintain the overall shape. While this new mesh may look closer to the old one, it will likely create new vertices, implying that our total number of rows in the

In [14]:
ms_2 = pymeshlab.MeshSet()
ms_2.load_new_mesh('../../../models/foot/human-foot.obj')

ms_2.meshing_decimation_quadric_edge_collapse(optimalplacement=True) #reverting this to True

m_test = ms_2.current_mesh()
v_matrix_test = m_test.vertex_matrix()

vertex_df_test = pd.DataFrame(v_matrix_test, columns = ["X", "Y", "Z"])

vertex_df_test['coords'] = vertex_df_test[["X", "Y", "Z"]].apply(tuple, axis=1)

test_df_vertex = pd.merge(vertex_df, vertex_df_test, how="outer", on="coords")
len(test_df_vertex)

975

As expected, we see an increase in the number of vertices, implying that we are creating new ones.

## Main Workflow

How do we maintain the same vertex index structure between our meshes? By default, this is not possible. Indices are assigned at generation. However, we know that the coordinates of our vertices are the same. We can use these coordinates as our primary key between the two meshes and renormalize our indices based on that.

Since our decimated mesh is a subset of the original, we can guarantee that every vertex in this mesh will exist in the original. By this logic, we shall renormalize our original mesh based on the vertices from the decimated one. Here is a visual that explains this.

The main workflow we'd like to implement is as follows:

1) load the raw obj file to pymeshlab data.
2) make note of the vertices and their raw indicies
3) decimate our mesh using the `optimalposition=False` parameter
4) create a merged dataframe joining based on the coordinate info
5) map the vertex indices based on pre-tranformation index --> post transformation index.
6) recreate the face dataframe based on these new vertices.

In theory, this process should maintain the shape of both meshes (original and decimated), while ensuring index consistency across their geometry. This should solve our problem statement in the markdown file [mesh-simplification.md](../mesh-simplification.md).

Eventually, this will be converted in to script format and called recursively to create these decimated meshes on demand.

Let's start by clearing data from our `MeshSet` object.

In [15]:
ms.clear()

We load our foot model once again.

In [16]:
ms.load_new_mesh('../../../models/foot/human-foot.obj')

Let's get our baseline vertices and faces, and convert those to dataframe.

In [17]:
m = ms.current_mesh()

v_matrix_bs = m.vertex_matrix()
f_matrix_bs = m.face_matrix()

baseline_vertex_df = pd.DataFrame(v_matrix_bs, columns = ["X", "Y", "Z"])
baseline_face_df = pd.DataFrame(f_matrix_bs, columns = ["v1", "v2", "v3"])

baseline_vertex_df.head()

          X         Y         Z
0  0.059608  0.383419 -0.047925
1 -0.030599 -0.016010 -0.020009
2  0.052395  0.402345  0.102574
3  0.049393 -0.015811 -0.022423
4 -0.061567  0.421855 -0.066727

In [18]:
baseline_face_df.head()

    v1   v2   v3
0  715   31   33
1  715   33  712
2   86   16   17
3   86   17   83
4   59  795  796

As a reminder, the `face` dataframe contains references to the index of the specific vertex that makes up its 3 corners.

Let's proceed with decimating our mesh, remembering to set the `optimalplacement` parameter equal to `False`.

In [19]:
ms.meshing_decimation_quadric_edge_collapse(optimalplacement=False)

Now, the vertices and faces corresponding to this mesh will be that of our decimated object. This means less numbers of vertices, and the indices will not align. We extract this information out and run some tests to verify that this is the case.

In [20]:
m = ms.current_mesh()

v_matrix_dm = m.vertex_matrix()
f_matrix_dm = m.face_matrix()

decimated_vertex_df = pd.DataFrame(v_matrix_dm, columns = ["X", "Y", "Z"])
decimated_face_df = pd.DataFrame(f_matrix_dm, columns = ["v1", "v2", "v3"])

len(decimated_vertex_df)

403

In [21]:
len(decimated_face_df)

792

We now apply our concatentation step from above.

In [22]:
decimated_vertex_df["coords"] = decimated_vertex_df[["X", "Y", "Z"]].apply(tuple, axis=1)
baseline_vertex_df["coords"] = baseline_vertex_df[["X", "Y", "Z"]].apply(tuple, axis=1)

In these 2 dataframes, our `coords` column serves as a unique key, given that no 2 vertices overlap with each other. In this case, it might be best to set this column as our index.

In [23]:
baseline_vertex_df["vertex_index"] = baseline_vertex_df.index
baseline_vertex_df = baseline_vertex_df.set_index("coords")

decimated_vertex_df["vertex_index"] = decimated_vertex_df.index
decimated_vertex_df = decimated_vertex_df.set_index("coords")

baseline_vertex_df.head()

                                         X         Y         Z  vertex_index
coords
(0.059608, 0.383419, -0.047925)   0.059608  0.383419 -0.047925             0
(-0.030599, -0.01601, -0.020009) -0.030599 -0.016010 -0.020009             1
(0.052395, 0.402345, 0.102574)    0.052395  0.402345  0.102574             2
(0.049393, -0.015811, -0.022423)  0.049393 -0.015811 -0.022423             3
(-0.061567, 0.421855, -0.066727) -0.061567  0.421855 -0.066727             4

We now perform a merge based on the index of both our columns.

In [24]:
merged_df_vertex = pd.merge(baseline_vertex_df, decimated_vertex_df, left_index=True, right_index=True, how="outer")
merged_df_vertex.head()

,X_x,Y_x,Z_x,vertex_index_x,X_y,Y_y,Z_y,vertex_index_y
coords,,,,,,,,
"(-0.224832, 0.030038, 0.526462)",-0.224832,0.030038,0.526462,645,-0.224832,0.030038,0.526462,325.0
"(-0.223318, 0.034579, 0.441157)",-0.223318,0.034579,0.441157,98,-0.223318,0.034579,0.441157,92.0
"(-0.22168, 0.043812, 0.651764)",-0.221680,0.043812,0.651764,299,-0.221680,0.043812,0.651764,193.0
"(-0.221125, 0.076088, 0.533599)",-0.221125,0.076088,0.533599,644,-0.221125,0.076088,0.533599,324.0
"(-0.22075, 0.085796, 0.448143)",-0.220750,0.085796,0.448143,99,-0.220750,0.085796,0.448143,93.0

We now have a mapping of our vertices from the original mesh to the decimated one. The goal is to treat the decimated one as "ground truth" and extrapolate from there. Here, we first sort by our decimated mesh's index and reset the index of our overall dataframe.

In [25]:
merged_df_vertex = merged_df_vertex.sort_values(by="vertex_index_y")
merged_df_vertex = merged_df_vertex.reset_index()
merged_df_vertex

,coords,X_x,Y_x,Z_x,vertex_index_x,X_y,Y_y,Z_y,vertex_index_y
0,"(0.059608, 0.383419, -0.047925)",0.059608,0.383419,-0.047925,0,0.059608,0.383419,-0.047925,0.0
1,"(-0.030599, -0.01601, -0.020009)",-0.030599,-0.016010,-0.020009,1,-0.030599,-0.016010,-0.020009,1.0
2,"(0.052395, 0.402345, 0.102574)",0.052395,0.402345,0.102574,2,0.052395,0.402345,0.102574,2.0
3,"(0.049393, -0.015811, -0.022423)",0.049393,-0.015811,-0.022423,3,0.049393,-0.015811,-0.022423,3.0
4,"(-0.061567, 0.421855, -0.066727)",-0.061567,0.421855,-0.066727,4,-0.061567,0.421855,-0.066727,4.0
...,...,...,...,...,...,...,...,...,...
795,"(0.15269, 0.044007, 0.587606)",0.152690,0.044007,0.587606,775,NaN,NaN,NaN,NaN
796,"(0.154933, 0.074872, 0.516165)",0.154933,0.074872,0.516165,109,NaN,NaN,NaN,NaN
797,"(0.157481, 0.015595, 0.408668)",0.157481,0.015595,0.408668,795,NaN,NaN,NaN,NaN
798,"(0.163158, 0.035477, 0.397872)",0.163158,0.035477,0.397872,798,NaN,NaN,NaN,NaN
799,"(0.163247, 0.081139, 0.437404)",0.163247,0.081139,0.437404,92,NaN,NaN,NaN,NaN

In [26]:
assert 235 == int(merged_df_vertex.loc[235]["vertex_index_y"])

This merged_df essentially serves as a map from our decimated mesh index space to our original mesh index space.

In [27]:
mapping_dict = {}

for i in merged_df_vertex.index:
    mapping_dict[ merged_df_vertex.loc[i]["vertex_index_x"] ] = i

mapping_dict

{np.int64(0): 0,
 np.int64(1): 1,
 np.int64(2): 2,
 np.int64(3): 3,
 np.int64(4): 4,
 np.int64(5): 5,
 np.int64(6): 6,
 np.int64(7): 7,
 np.int64(8): 8,
 np.int64(9): 9,
 np.int64(10): 10,
 np.int64(11): 11,
 np.int64(12): 12,
 np.int64(14): 13,
 np.int64(15): 14,
 np.int64(16): 15,
 np.int64(17): 16,
 np.int64(18): 17,
 np.int64(19): 18,
 np.int64(20): 19,
 np.int64(21): 20,
 np.int64(22): 21,
 np.int64(23): 22,
 np.int64(25): 23,
 np.int64(26): 24,
 np.int64(28): 25,
 np.int64(29): 26,
 np.int64(30): 27,
 np.int64(31): 28,
 np.int64(32): 29,
 np.int64(33): 30,
 np.int64(34): 31,
 np.int64(35): 32,
 np.int64(36): 33,
 np.int64(37): 34,
 np.int64(38): 35,
 np.int64(39): 36,
 np.int64(40): 37,
 np.int64(41): 38,
 np.int64(42): 39,
 np.int64(43): 40,
 np.int64(45): 41,
 np.int64(46): 42,
 np.int64(47): 43,
 np.int64(48): 44,
 np.int64(49): 45,
 np.int64(50): 46,
 np.int64(51): 47,
 np.int64(52): 48,
 np.int64(53): 49,
 np.int64(54): 50,
 np.int64(55): 51,
 np.int64(56): 52,
 np.int64(57): 53,
 np.int64(58): 54,
 np.int64(59): 55,
 np.int64(60): 56,
 np.int64(61): 57,
 np.int64(62): 58,
 np.int64(63): 59,
 np.int64(64): 60,
 np.int64(65): 61,
 np.int64(66): 62,
 np.int64(67): 63,
 np.int64(68): 64,
 np.int64(69): 65,
 np.int64(70): 66,
 np.int64(71): 67,
 np.int64(72): 68,
 np.int64(73): 69,
 np.int64(75): 70,
 np.int64(76): 71,
 np.int64(77): 72,
 np.int64(78): 73,
 np.int64(79): 74,
 np.int64(80): 75,
 np.int64(81): 76,
 np.int64(82): 77,
 np.int64(83): 78,
 np.int64(84): 79,
 np.int64(85): 80,
 np.int64(86): 81,
 np.int64(87): 82,
 np.int64(88): 83,
 np.int64(89): 84,
 np.int64(90): 85,
 np.int64(91): 86,
 np.int64(93): 87,
 np.int64(94): 88,
 np.int64(95): 89,
 np.int64(96): 90,
 np.int64(97): 91,
 np.int64(98): 92,
 np.int64(99): 93,
 np.int64(100): 94,
 np.int64(101): 95,
 np.int64(102): 96,
 np.int64(103): 97,
 np.int64(104): 98,
 np.int64(106): 99,
 np.int64(107): 100,
 np.int64(108): 101,
 np.int64(110): 102,
 np.int64(112): 103,
 np.int64(113): 104,
 np.int64(114): 105,
 np.int64(115): 106,
 np.int64(116): 107,
 np.int64(117): 108,
 np.int64(118): 109,
 np.int64(119): 110,
 np.int64(120): 111,
 np.int64(121): 112,
 np.int64(122): 113,
 np.int64(123): 114,
 np.int64(124): 115,
 np.int64(125): 116,
 np.int64(126): 117,
 np.int64(127): 118,
 np.int64(128): 119,
 np.int64(129): 120,
 np.int64(130): 121,
 np.int64(131): 122,
 np.int64(132): 123,
 np.int64(133): 124,
 np.int64(134): 125,
 np.int64(135): 126,
 np.int64(137): 127,
 np.int64(138): 128,
 np.int64(141): 129,
 np.int64(142): 130,
 np.int64(146): 131,
 np.int64(158): 132,
 np.int64(160): 133,
 np.int64(169): 134,
 np.int64(171): 135,
 np.int64(176): 136,
 np.int64(180): 137,
 np.int64(181): 138,
 np.int64(185): 139,
 np.int64(188): 140,
 np.int64(192): 141,
 np.int64(194): 142,
 np.int64(195): 143,
 np.int64(196): 144,
 np.int64(197): 145,
 np.int64(198): 146,
 np.int64(203): 147,
 np.int64(206): 148,
 np.int64(208): 149,
 np.int64(217): 150,
 np.int64(223): 151,
 np.int64(227): 152,
 np.int64(235): 153,
 np.int64(236): 154,
 np.int64(237): 155,
 np.int64(239): 156,
 np.int64(240): 157,
 np.int64(242): 158,
 np.int64(245): 159,
 np.int64(246): 160,
 np.int64(247): 161,
 np.int64(248): 162,
 np.int64(249): 163,
 np.int64(250): 164,
 np.int64(251): 165,
 np.int64(252): 166,
 np.int64(253): 167,
 np.int64(258): 168,
 np.int64(259): 169,
 np.int64(261): 170,
 np.int64(262): 171,
 np.int64(263): 172,
 np.int64(265): 173,
 np.int64(266): 174,
 np.int64(267): 175,
 np.int64(273): 176,
 np.int64(274): 177,
 np.int64(278): 178,
 np.int64(279): 179,
 np.int64(281): 180,
 np.int64(282): 181,
 np.int64(284): 182,
 np.int64(285): 183,
 np.int64(287): 184,
 np.int64(288): 185,
 np.int64(289): 186,
 np.int64(290): 187,
 np.int64(291): 188,
 np.int64(292): 189,
 np.int64(293): 190,
 np.int64(297): 191,
 np.int64(298): 192,
 np.int64(299): 193,
 np.int64(305): 194,
 np.int64(306): 195,
 np.int64(308): 196,
 np.int64(310): 197,
 np.int64(313): 198,
 np.int64(315): 199,
 np.int64(317): 200,
 np.int64(318): 201,
 np.int64(319): 202,
 np.int64(320): 203,
 np.int64(321): 204,
 np.int64(322): 205,
 np.int64(323): 206,
 np.int64(330): 207,
 np.int64(334): 208,
 np.int64(335): 209,
 np.int64(336): 210,
 np.int64(337): 211,
 np.int64(338): 212,
 np.int64(343): 213,
 np.int64(346): 214,
 np.int64(348): 215,
 np.int64(350): 216,
 np.int64(356): 217,
 np.int64(362): 218,
 np.int64(363): 219,
 np.int64(364): 220,
 np.int64(366): 221,
 np.int64(367): 222,
 np.int64(368): 223,
 np.int64(371): 224,
 np.int64(375): 225,
 np.int64(381): 226,
 np.int64(382): 227,
 np.int64(383): 228,
 np.int64(384): 229,
 np.int64(385): 230,
 np.int64(386): 231,
 np.int64(387): 232,
 np.int64(388): 233,
 np.int64(389): 234,
 np.int64(394): 235,
 np.int64(395): 236,
 np.int64(396): 237,
 np.int64(399): 238,
 np.int64(400): 239,
 np.int64(401): 240,
 np.int64(403): 241,
 np.int64(405): 242,
 np.int64(411): 243,
 np.int64(414): 244,
 np.int64(415): 245,
 np.int64(417): 246,
 np.int64(419): 247,
 np.int64(424): 248,
 np.int64(425): 249,
 np.int64(426): 250,
 np.int64(427): 251,
 np.int64(428): 252,
 np.int64(429): 253,
 np.int64(437): 254,
 np.int64(438): 255,
 np.int64(440): 256,
 np.int64(441): 257,
 np.int64(455): 258,
 np.int64(461): 259,
 np.int64(463): 260,
 np.int64(465): 261,
 np.int64(466): 262,
 np.int64(470): 263,
 np.int64(471): 264,
 np.int64(474): 265,
 np.int64(475): 266,
 np.int64(479): 267,
 np.int64(486): 268,
 np.int64(487): 269,
 np.int64(489): 270,
 np.int64(490): 271,
 np.int64(491): 272,
 np.int64(492): 273,
 np.int64(498): 274,
 np.int64(500): 275,
 np.int64(503): 276,
 np.int64(508): 277,
 np.int64(518): 278,
 np.int64(519): 279,
 np.int64(521): 280,
 np.int64(523): 281,
 np.int64(528): 282,
 np.int64(530): 283,
 np.int64(531): 284,
 np.int64(532): 285,
 np.int64(533): 286,
 np.int64(534): 287,
 np.int64(541): 288,
 np.int64(544): 289,
 np.int64(545): 290,
 np.int64(549): 291,
 np.int64(554): 292,
 np.int64(556): 293,
 np.int64(558): 294,
 np.int64(559): 295,
 np.int64(574): 296,
 np.int64(575): 297,
 np.int64(576): 298,
 np.int64(578): 299,
 np.int64(579): 300,
 np.int64(583): 301,
 np.int64(590): 302,
 np.int64(591): 303,
 np.int64(593): 304,
 np.int64(595): 305,
 np.int64(596): 306,
 np.int64(604): 307,
 np.int64(607): 308,
 np.int64(614): 309,
 np.int64(619): 310,
 np.int64(622): 311,
 np.int64(623): 312,
 np.int64(627): 313,
 np.int64(632): 314,
 np.int64(634): 315,
 np.int64(635): 316,
 np.int64(636): 317,
 np.int64(638): 318,
 np.int64(639): 319,
 np.int64(640): 320,
 np.int64(641): 321,
 np.int64(642): 322,
 np.int64(643): 323,
 np.int64(644): 324,
 np.int64(645): 325,
 np.int64(646): 326,
 np.int64(648): 327,
 np.int64(649): 328,
 np.int64(650): 329,
 np.int64(656): 330,
 np.int64(658): 331,
 np.int64(661): 332,
 np.int64(664): 333,
 np.int64(665): 334,
 np.int64(666): 335,
 np.int64(667): 336,
 np.int64(668): 337,
 np.int64(670): 338,
 np.int64(671): 339,
 np.int64(673): 340,
 np.int64(680): 341,
 np.int64(681): 342,
 np.int64(683): 343,
 np.int64(684): 344,
 np.int64(685): 345,
 np.int64(686): 346,
 np.int64(688): 347,
 np.int64(690): 348,
 np.int64(691): 349,
 np.int64(692): 350,
 np.int64(693): 351,
 np.int64(694): 352,
 np.int64(695): 353,
 np.int64(696): 354,
 np.int64(697): 355,
 np.int64(698): 356,
 np.int64(699): 357,
 np.int64(702): 358,
 np.int64(705): 359,
 np.int64(707): 360,
 np.int64(708): 361,
 np.int64(711): 362,
 np.int64(712): 363,
 np.int64(713): 364,
 np.int64(714): 365,
 np.int64(715): 366,
 np.int64(716): 367,
 np.int64(717): 368,
 np.int64(718): 369,
 np.int64(719): 370,
 np.int64(720): 371,
 np.int64(721): 372,
 np.int64(722): 373,
 np.int64(723): 374,
 np.int64(724): 375,
 np.int64(725): 376,
 np.int64(726): 377,
 np.int64(727): 378,
 np.int64(728): 379,
 np.int64(729): 380,
 np.int64(730): 381,
 np.int64(731): 382,
 np.int64(732): 383,
 np.int64(733): 384,
 np.int64(734): 385,
 np.int64(735): 386,
 np.int64(736): 387,
 np.int64(737): 388,
 np.int64(738): 389,
 np.int64(739): 390,
 np.int64(740): 391,
 np.int64(744): 392,
 np.int64(778): 393,
 np.int64(785): 394,
 np.int64(786): 395,
 np.int64(788): 396,
 np.int64(791): 397,
 np.int64(792): 398,
 np.int64(793): 399,
 np.int64(794): 400,
 np.int64(796): 401,
 np.int64(797): 402,
 np.int64(314): 403,
 np.int64(295): 404,
 np.int64(304): 405,
 np.int64(309): 406,
 np.int64(300): 407,
 np.int64(302): 408,
 np.int64(311): 409,
 np.int64(312): 410,
 np.int64(296): 411,
 np.int64(303): 412,
 np.int64(316): 413,
 np.int64(301): 414,
 np.int64(307): 415,
 np.int64(294): 416,
 np.int64(275): 417,
 np.int64(283): 418,
 np.int64(270): 419,
 np.int64(254): 420,
 np.int64(271): 421,
 np.int64(269): 422,
 np.int64(244): 423,
 np.int64(74): 424,
 np.int64(257): 425,
 np.int64(286): 426,
 np.int64(243): 427,
 np.int64(264): 428,
 np.int64(255): 429,
 np.int64(256): 430,
 np.int64(268): 431,
 np.int64(280): 432,
 np.int64(272): 433,
 np.int64(276): 434,
 np.int64(241): 435,
 np.int64(277): 436,
 np.int64(260): 437,
 np.int64(706): 438,
 np.int64(700): 439,
 np.int64(701): 440,
 np.int64(743): 441,
 np.int64(420): 442,
 np.int64(421): 443,
 np.int64(410): 444,
 np.int64(761): 445,
 np.int64(391): 446,
 np.int64(392): 447,
 np.int64(652): 448,
 np.int64(764): 449,
 np.int64(409): 450,
 np.int64(393): 451,
 np.int64(710): 452,
 np.int64(422): 453,
 np.int64(404): 454,
 np.int64(418): 455,
 np.int64(763): 456,
 np.int64(412): 457,
 np.int64(742): 458,
 np.int64(413): 459,
 np.int64(406): 460,
 np.int64(407): 461,
 np.int64(762): 462,
 np.int64(651): 463,
 np.int64(398): 464,
 np.int64(408): 465,
 np.int64(423): 466,
 np.int64(416): 467,
 np.int64(397): 468,
 np.int64(709): 469,
 np.int64(402): 470,
 np.int64(390): 471,
 np.int64(741): 472,
 np.int64(345): 473,
 np.int64(358): 474,
 np.int64(380): 475,
 np.int64(379): 476,
 np.int64(353): 477,
 np.int64(324): 478,
 np.int64(354): 479,
 np.int64(361): 480,
 np.int64(757): 481,
 np.int64(352): 482,
 np.int64(357): 483,
 np.int64(328): 484,
 np.int64(372): 485,
 np.int64(333): 486,
 np.int64(760): 487,
 np.int64(344): 488,
 np.int64(44): 489,
 np.int64(799): 490,
 np.int64(327): 491,
 np.int64(347): 492,
 np.int64(369): 493,
 np.int64(339): 494,
 np.int64(340): 495,
 np.int64(756): 496,
 np.int64(351): 497,
 np.int64(355): 498,
 np.int64(378): 499,
 np.int64(374): 500,
 np.int64(325): 501,
 np.int64(365): 502,
 np.int64(758): 503,
 np.int64(349): 504,
 np.int64(647): 505,
 np.int64(370): 506,
 np.int64(373): 507,
 np.int64(687): 508,
 np.int64(331): 509,
 np.int64(342): 510,
 np.int64(755): 511,
 np.int64(759): 512,
 np.int64(332): 513,
 np.int64(329): 514,
 np.int64(359): 515,
 np.int64(377): 516,
 np.int64(376): 517,
 np.int64(360): 518,
 np.int64(689): 519,
 np.int64(326): 520,
 np.int64(341): 521,
 np.int64(703): 522,
 np.int64(704): 523,
 np.int64(493): 524,
 np.int64(499): 525,
 np.int64(514): 526,
 np.int64(524): 527,
 np.int64(495): 528,
 np.int64(505): 529,
 np.int64(497): 530,
 np.int64(513): 531,
 np.int64(496): 532,
 np.int64(525): 533,
 np.int64(507): 534,
 np.int64(504): 535,
 np.int64(516): 536,
 np.int64(751): 537,
 np.int64(27): 538,
 np.int64(754): 539,
 np.int64(517): 540,
 np.int64(529): 541,
 np.int64(515): 542,
 np.int64(526): 543,
 np.int64(522): 544,
 np.int64(509): 545,
 np.int64(511): 546,
 np.int64(510): 547,
 np.int64(752): 548,
 np.int64(753): 549,
 np.int64(502): 550,
 np.int64(512): 551,
 np.int64(501): 552,
 np.int64(520): 553,
 np.int64(657): 554,
 np.int64(506): 555,
 np.int64(527): 556,
 np.int64(494): 557,
 np.int64(450): 558,
 np.int64(434): 559,
 np.int64(448): 560,
 np.int64(468): 561,
 np.int64(476): 562,
 np.int64(472): 563,
 np.int64(750): 564,
 np.int64(442): 565,
 np.int64(483): 566,
 np.int64(747): 567,
 np.int64(484): 568,
 np.int64(458): 569,
 np.int64(457): 570,
 np.int64(432): 571,
 np.int64(462): 572,
 np.int64(456): 573,
 np.int64(449): 574,
 np.int64(790): 575,
 np.int64(485): 576,
 np.int64(473): 577,
 np.int64(451): 578,
 np.int64(431): 579,
 np.int64(443): 580,
 np.int64(444): 581,
 np.int64(478): 582,
 np.int64(746): 583,
 np.int64(454): 584,
 np.int64(482): 585,
 np.int64(679): 586,
 np.int64(460): 587,
 np.int64(467): 588,
 np.int64(459): 589,
 np.int64(446): 590,
 np.int64(748): 591,
 np.int64(477): 592,
 np.int64(452): 593,
 np.int64(469): 594,
 np.int64(453): 595,
 np.int64(676): 596,
 np.int64(435): 597,
 np.int64(654): 598,
 np.int64(675): 599,
 np.int64(439): 600,
 np.int64(433): 601,
 np.int64(430): 602,
 np.int64(436): 603,
 np.int64(447): 604,
 np.int64(464): 605,
 np.int64(745): 606,
 np.int64(653): 607,
 np.int64(445): 608,
 np.int64(749): 609,
 np.int64(480): 610,
 np.int64(481): 611,
 np.int64(488): 612,
 np.int64(111): 613,
 np.int64(600): 614,
 np.int64(597): 615,
 np.int64(603): 616,
 np.int64(677): 617,
 np.int64(678): 618,
 np.int64(618): 619,
 np.int64(609): 620,
 np.int64(599): 621,
 np.int64(617): 622,
 np.int64(611): 623,
 np.int64(601): 624,
 np.int64(13): 625,
 np.int64(602): 626,
 np.int64(608): 627,
 np.int64(612): 628,
 np.int64(620): 629,
 np.int64(613): 630,
 np.int64(615): 631,
 np.int64(629): 632,
 np.int64(621): 633,
 np.int64(628): 634,
 np.int64(616): 635,
 np.int64(606): 636,
 np.int64(630): 637,
 np.int64(774): 638,
 np.int64(605): 639,
 np.int64(625): 640,
 np.int64(655): 641,
 np.int64(610): 642,
 np.int64(771): 643,
 np.int64(772): 644,
 np.int64(663): 645,
 np.int64(598): 646,
 np.int64(633): 647,
 np.int64(626): 648,
 np.int64(538): 649,
 np.int64(624): 650,
 np.int64(773): 651,
 np.int64(631): 652,
 np.int64(561): 653,
 np.int64(536): 654,
 np.int64(565): 655,
 np.int64(566): 656,
 np.int64(560): 657,
 np.int64(562): 658,
 np.int64(552): 659,
 np.int64(553): 660,
 np.int64(569): 661,
 np.int64(572): 662,
 np.int64(546): 663,
 np.int64(587): 664,
 np.int64(662): 665,
 np.int64(535): 666,
 np.int64(588): 667,
 np.int64(555): 668,
 np.int64(580): 669,
 np.int64(547): 670,
 np.int64(564): 671,
 np.int64(789): 672,
 np.int64(787): 673,
 np.int64(770): 674,
 np.int64(767): 675,
 np.int64(594): 676,
 np.int64(548): 677,
 np.int64(563): 678,
 np.int64(577): 679,
 np.int64(557): 680,
 np.int64(542): 681,
 np.int64(589): 682,
 np.int64(570): 683,
 np.int64(586): 684,
 np.int64(539): 685,
 np.int64(573): 686,
 np.int64(24): 687,
 np.int64(551): 688,
 np.int64(582): 689,
 np.int64(571): 690,
 np.int64(550): 691,
 np.int64(581): 692,
 np.int64(537): 693,
 np.int64(660): 694,
 np.int64(540): 695,
 np.int64(768): 696,
 np.int64(567): 697,
 np.int64(766): 698,
 np.int64(543): 699,
 np.int64(568): 700,
 np.int64(584): 701,
 np.int64(211): 702,
 np.int64(585): 703,
 np.int64(204): 704,
 np.int64(765): 705,
 np.int64(769): 706,
 np.int64(213): 707,
 np.int64(659): 708,
 np.int64(592): 709,
 np.int64(201): 710,
 np.int64(200): 711,
 np.int64(207): 712,
 np.int64(216): 713,
 np.int64(218): 714,
 np.int64(205): 715,
 np.int64(222): 716,
 np.int64(215): 717,
 np.int64(219): 718,
 np.int64(220): 719,
 np.int64(682): 720,
 np.int64(221): 721,
 np.int64(212): 722,
 np.int64(669): 723,
 np.int64(674): 724,
 np.int64(226): 725,
 np.int64(672): 726,
 np.int64(202): 727,
 np.int64(210): 728,
 np.int64(209): 729,
 np.int64(224): 730,
 np.int64(136): 731,
 np.int64(225): 732,
 np.int64(214): 733,
 np.int64(233): 734,
 np.int64(145): 735,
 np.int64(232): 736,
 np.int64(234): 737,
 np.int64(140): 738,
 np.int64(231): 739,
 np.int64(148): 740,
 np.int64(238): 741,
 np.int64(229): 742,
 np.int64(784): 743,
 np.int64(782): 744,
 np.int64(781): 745,
 np.int64(164): 746,
 np.int64(230): 747,
 np.int64(166): 748,
 np.int64(228): 749,
 np.int64(783): 750,
 np.int64(165): 751,
 np.int64(156): 752,
 np.int64(170): 753,
 np.int64(183): 754,
 np.int64(139): 755,
 np.int64(184): 756,
 np.int64(157): 757,
 np.int64(168): 758,
 np.int64(199): 759,
 np.int64(150): 760,
 np.int64(151): 761,
 np.int64(163): 762,
 np.int64(159): 763,
 np.int64(780): 764,
 np.int64(777): 765,
 np.int64(143): 766,
 np.int64(167): 767,
 np.int64(173): 768,
 np.int64(187): 769,
 np.int64(152): 770,
 np.int64(161): 771,
 np.int64(149): 772,
 np.int64(191): 773,
 np.int64(162): 774,
 np.int64(155): 775,
 np.int64(154): 776,
 np.int64(153): 777,
 np.int64(177): 778,
 np.int64(175): 779,
 np.int64(193): 780,
 np.int64(776): 781,
 np.int64(182): 782,
 np.int64(174): 783,
 np.int64(637): 784,
 np.int64(186): 785,
 np.int64(144): 786,
 np.int64(190): 787,
 np.int64(105): 788,
 np.int64(147): 789,
 np.int64(779): 790,
 np.int64(172): 791,
 np.int64(189): 792,
 np.int64(178): 793,
 np.int64(179): 794,
 np.int64(775): 795,
 np.int64(109): 796,
 np.int64(795): 797,
 np.int64(798): 798,
 np.int64(92): 799}

Now we recreate our face dataframe from the original mesh using this transformed index space. As a reminder, here is what the original dataframe looks like.

In [28]:
baseline_face_df_reconstruct = baseline_face_df.copy()
baseline_face_df_reconstruct.head()

    v1   v2   v3
0  715   31   33
1  715   33  712
2   86   16   17
3   86   17   83
4   59  795  796

Now, we map these original values to the new ones using the `.map()` method and our created mapping dictionary.

In [29]:
baseline_face_df_reconstruct["v1_new"] = baseline_face_df_reconstruct["v1"].map(mapping_dict)
baseline_face_df_reconstruct.head()

    v1   v2   v3  v1_new
0  715   31   33     366
1  715   33  712     366
2   86   16   17      81
3   86   17   83      81
4   59  795  796      55

Let's confirm that the mapping went as expected.

In [30]:
assert baseline_face_df_reconstruct.loc[0]["v1_new"] == mapping_dict[baseline_face_df_reconstruct.loc[0]["v1"]]
assert baseline_face_df_reconstruct.loc[7]["v1_new"] == mapping_dict[baseline_face_df_reconstruct.loc[7]["v1"]]

Looks good, let's map the rest of the vertices as well.

In [31]:
baseline_face_df_reconstruct["v2_new"] = baseline_face_df_reconstruct["v2"].map(mapping_dict)
baseline_face_df_reconstruct["v3_new"] = baseline_face_df_reconstruct["v3"].map(mapping_dict)

baseline_face_df_reconstruct.head()

    v1   v2   v3  v1_new  v2_new  v3_new
0  715   31   33     366      28      30
1  715   33  712     366      30     363
2   86   16   17      81      15      16
3   86   17   83      81      16      78
4   59  795  796      55     797     401

Perfect. We have successfully remapped our original face dataframe.

## Reconversion to OBJ file

Now, its time to export these meshes out to new OBJ files that share the same geometry array structure. First, we need to extract the corresponding information out from our merged dataframes. Here is the data we need.

1) vertex array for original mesh: This data is saved in our `merged_df_vertex` in the columns "X_x", "Y_x", "Z_x". 
2) vertex array for decimated mesh: This data will be the original `v_matrix_dm` object we created after decimation.
3) face array for the original mesh: This data is saved in `baseline_face_df_reconstruct` in the columns "v1_new", "v2_new", "v3_new"
4) face array for the decimated mesh: This data is the original face array from our decimated mesh `f_matrix_dm`. As a reminder, this dataset correctly references our decimated mesh's indices.

We need to convert dataframes to numpy.

In [32]:
v_full = merged_df_vertex[["X_x", "Y_x", "Z_x"]].to_numpy()
v_dec = v_matrix_dm

f_full = baseline_face_df_reconstruct[["v1_new", "v2_new", "v3_new"]].to_numpy()
f_dec = f_matrix_dm

Creating a mesh involves passing the Vertex and Face array to a `Mesh()` class in pymeshlab.

In [33]:
# Create new meshes in pymeshlab by passing the arguments (vertex_array, faces_array)
m_orig = pymeshlab.Mesh(v_full, f_full)
m_dec = pymeshlab.Mesh(v_dec, f_dec)

Now, lets convert to obj file. First, we add the mesh to our Meshset() object.

In [34]:
ms.add_mesh(m_orig, "OriginalMesh")
ms.save_current_mesh("models" + "original_mesh.obj")

In [35]:
ms.add_mesh(m_dec, "DecimatedMesh")
ms.save_current_mesh("models" + "decimated_mesh.obj")

And what do these meshes look like? We load both files into Blender.

![Results of the Reconstructed OBJ file](../img/optimized-decimate-script-results.png)

Fantastic results. We see that the decimation has occured and removed the bulk of vertices in high concentration areas, specifically the toes. Now its time to see if our vertex array is truly shared between these meshes.

Loading the 2 meshes into the MeshLab application, this is what we observe.

![Vertex Indices match across indices in MeshLab](../img/same-vertex-index-after-decimation.png)

The vertex number 174 is common across both meshes.

Moreover, we load our two meshes as [LOD's to our BatchedMesh object in three.js](../../optimizing-the-scene/batchedmesh-with-LOD.md) scene. In this scene, our low resolution mesh is set as a lower resoultion LOD of the higher resolution one. The meshes are triggered to switch at a distance of 5 units from the camera. Here are the results.

The results were exactly what we'd hoped for, so its very good news that our method is now working.

Let's try other values for the mesh quality.

## Convert to Module

It is now time to save this as a module which we can call on other meshes. Let us recall the order of steps which needs to be conducted from the work above.

1) Load OBJ file to memory.
2) Get vertex and face arrays
3) Apply `ms.meshing_decimation_quadric_edge_collapse(optimalplacement=False)` algorithm on the mesh
4) Get decimated mesh's vertex and face arrays
5) Merge both arrays based on the coordinates of each vertex (should be UID for both)
6) Renormalize original mesh to decimated mesh's index structure

We shall create a basic structure of the function here, and then export it our to a module.

As a reminder, here are the basic list of commands we sent to create our reconstrution.

In [36]:
# ms.load_new_mesh(obj_path)
# m = ms.current_mesh()

# v_matrix_bs = m.vertex_matrix()
# f_matrix_bs = m.face_matrix()

# baseline_vertex_df = pd.DataFrame(v_matrix_bs, columns = ["X", "Y", "Z"])
# baseline_face_df = pd.DataFrame(f_matrix_bs, columns = ["v1", "v2", "v3"])

# ms.meshing_decimation_quadric_edge_collapse(optimalplacement=False)

# m = ms.current_mesh()

# v_matrix_dm = m.vertex_matrix()
# f_matrix_dm = m.face_matrix()

# decimated_vertex_df = pd.DataFrame(v_matrix_dm, columns = ["X", "Y", "Z"])
# decimated_face_df = pd.DataFrame(f_matrix_dm, columns = ["v1", "v2", "v3"])

# decimated_vertex_df["coords"] = decimated_vertex_df[["X", "Y", "Z"]].apply(tuple, axis=1)
# baseline_vertex_df["coords"] = baseline_vertex_df[["X", "Y", "Z"]].apply(tuple, axis=1)

# baseline_vertex_df["vertex_index"] = baseline_vertex_df.index
# baseline_vertex_df = baseline_vertex_df.set_index("coords")

# decimated_vertex_df["vertex_index"] = decimated_vertex_df.index
# decimated_vertex_df = decimated_vertex_df.set_index("coords")

# merged_df_vertex = pd.merge(baseline_vertex_df, decimated_vertex_df, left_index=True, right_index=True, how="outer")

# merged_df_vertex = merged_df_vertex.sort_values(by="vertex_index_y")
# merged_df_vertex = merged_df_vertex.reset_index()

# mapping_dict = {}

# for i in merged_df_vertex.index:
#     mapping_dict[ merged_df_vertex.loc[i]["vertex_index_x"] ] = i

# baseline_face_df_reconstruct = baseline_face_df.copy()

# baseline_face_df_reconstruct["v1_new"] = baseline_face_df_reconstruct["v1"].map(mapping_dict)

# assert baseline_face_df_reconstruct.loc[0]["v1_new"] == mapping_dict[baseline_face_df_reconstruct.loc[0]["v1"]]
# assert baseline_face_df_reconstruct.loc[7]["v1_new"] == mapping_dict[baseline_face_df_reconstruct.loc[7]["v1"]]

# baseline_face_df_reconstruct["v2_new"] = baseline_face_df_reconstruct["v2"].map(mapping_dict)
# baseline_face_df_reconstruct["v3_new"] = baseline_face_df_reconstruct["v3"].map(mapping_dict)

# v_full = merged_df_vertex[["X_x", "Y_x", "Z_x"]].to_numpy()
# v_dec = v_matrix_dm

# f_full = baseline_face_df_reconstruct[["v1_new", "v2_new", "v3_new"]].to_numpy()
# f_dec = f_matrix_dm

# m_orig = pymeshlab.Mesh(v_full, f_full)
# m_dec = pymeshlab.Mesh(v_dec, f_dec)

# ms.add_mesh(m_orig, "OriginalMesh")
# ms.save_current_mesh("models" + "original_mesh.obj")

# ms.add_mesh(m_dec, "DecimatedMesh")
# ms.save_current_mesh("models" + "decimated_mesh.obj")


# # print(dict(enumerate(v_dm)))

# #     combined_v = np.vstack((v_dm, v_org))

# #     unique_v, first_idx, inv_indices = np.unique(
# #         combined_v, axis=0, return_index=True, return_inverse=True, sorted=False
# #     )

#     # sort_order = np.argsort(first_idx)
#     # final_v_buffer = unique_v[sort_order]
    
#     # # 3. Create a re-mapping for the inversion
#     # # This aligns the inverse indices with the sorted unique buffer
#     # reindex_map = np.zeros_like(sort_order)
#     # reindex_map[sort_order] = np.arange(len(sort_order))
#     # final_mapping = reindex_map[inv_indices]

#     # # 4. Extract Face Matrices
#     # # f_dec: Since v_dm was at the front, its indices map to 0 -> len(v_dm)-1
#     # # Because we used return_index and sorted, the decimated indices remain 1:1
#     # f_dec_final = final_mapping[:len(v_dm)][np.arange(len(v_dm))][f_dm] 
    
#     # # f_orig: The original mesh now points to the combined buffer
#     # f_orig_mapping = final_mapping[len(v_dm):]
#     # f_orig_final = f_orig_mapping[f_org]

#     # m_orig = pymeshlab.Mesh(v_full, f_full)
#     # m_dec = pymeshlab.Mesh(v_dec, f_dec)

#     # ms.add_mesh(m_orig, "OriginalMesh")
#     # ms.save_current_mesh("models" + "original_mesh.obj")

#     # ms.add_mesh(m_dec, "DecimatedMesh")
#     # ms.save_current_mesh("models" + "decimated_mesh.obj")

I'd like to recreate this without pandas. Using only numpy, this problem becomes slightly more complex, but manageable. The basic structure of our function is as follows -->

- Get current object's vertex and face array (`v_org` and `f_org`)
- Apply decimation script with `optimalplacement=False`
- Get decimated mesh's vertex and face array (`v_dm` and `f_dm`)
- Create mapping dictionary- for each vertex in `v_dm`, save the coordinates as the key, and index as the map
- Iterate through every vertex in `v_org`, looking up the coordinates of each one in our mapping dictionary. If it exists, replace the element with the value from the map. If not, set to infinity.
- Sort this new array ascending. This means the vertex order will mimic that of the decimated mesh, while the infinity values will get appended to the end.
- Remap the original vertex and face arrays with this new order.

In [5]:
def decimate_mesh(obj_path, perc_red=0.0):
    v_dict = {}
    
    ms.load_new_mesh(obj_path)
    m = ms.current_mesh()
    
    v_org = m.vertex_matrix()
    f_org = m.face_matrix()

    ms.meshing_decimation_quadric_edge_collapse(targetperc=perc_red, optimalplacement=False)
    m = ms.current_mesh()

    v_dm = m.vertex_matrix()
    f_dm = m.face_matrix()

    v_dict = { tuple(row): i for i, row in enumerate(v_dm) }
    v_remapping = np.argsort(np.array([v_dict.get(tuple(row), np.inf) for row in v_org ]))

    v_org_rmp = v_org[v_remapping]
    f_org_rmp = v_remapping[f_org]

    assert v_org_rmp[:len(v_dm)].all() == v_dm.all()

    ms.clear()

    return v_org_rmp, f_org_rmp, v_dm, f_dm

In [38]:
v_recon, f_recon, v_dm, f_dm = decimate_mesh('../../../models/foot/human-foot.obj')

We include the following assert statement to ensure the function is working as intended.

In [39]:
assert v_recon[:len(v_dm)].all() == v_dm.all()

## Testing With Additional Meshes

Let's run some tests on this script with additional objects. I'm curious how this would work, especially with non manifold geometry. We shall be applying this function on the following 3 objects.

![Additional Testing on these objects](../img/decimation-additional-testing.png)

Object 1 is a valve handle. This object has intricately modelled geometry, and I expect a good decimated output from it.
Object 2 is a generic steel structure. I included this object since it already has a low count of vertices within it, and I'm curious to see how the decimation algorithm approaches it.
Object 3 is a generic pipe. This object is specially chosen since it has non manifold geometry- i.e. an open end. This mesh theoretically cannot exist in nature since on one side, we have only an open edge loop.

![Non Manifold Geometry Example](../img/non-manifold-geometry.png)

We observe in the figure above, one end of the pipe is simply a line segment. This will be a problem for applications like 3D printing, but pipes like these are littered around 3D models. Our function will need to handle this.

We start first, with our valve.

In [6]:
ms.clear()

v_recon_valve, f_recon_valve, v_dm_valve, f_dm_valve = decimate_mesh('../../../models/piperack/piperacks_valve only.obj')

Let's create a new set of meshes from this object and see what they look like.

In [7]:
valve_orig = pymeshlab.Mesh(v_recon_valve, f_recon_valve)
valve_dec = pymeshlab.Mesh(v_dm_valve, f_dm_valve)

ms.add_mesh(valve_orig, "OriginalMesh")
ms.save_current_mesh("valve_reconstruct.obj")

ms.add_mesh(valve_dec, "DecimatedMesh")
ms.save_current_mesh("valve_decimate.obj")

Loading them to Blender and MeshLab, this is what we see.

![Preliminary Results for Valve Decimation](../img/valve-decimation-first-results.png)

Not good. The object in the center is our decimated mesh, the object on the right is our original. We can see that the decimation occured properly- a visual indicator is the smoothness of the bolt in the middle of the valve.

However, the object on the right is the reconstructed version of the original, which looks completely wrong. It seems like the vertex indices have been messed up, we see the familiar "exploded" look that we saw when working initially with the [BatchedMeshLOD object](../../optimizing-the-scene/batchedmesh-with-LOD.md).

Let's inspect.

In [48]:
v_recon_valve

array([[-3.00117 ,  0.653368, -0.941665],
       [-3.001998,  0.674464, -0.941665],
       [-3.001998,  0.674464, -0.915417],
       ...,
       [-3.022813,  0.651252, -0.909043],
       [-3.011684,  0.672403, -0.909043],
       [-3.016895,  0.675144, -0.909043]], shape=(3606, 3))

In [47]:
v_dm_valve

array([[-3.00117 ,  0.653368, -0.941665],
       [-3.001998,  0.674464, -0.941665],
       [-3.001998,  0.674464, -0.915417],
       ...,
       [-3.057161,  0.451321, -0.804565],
       [-3.061818,  0.461098, -0.812225],
       [-3.062558,  0.454849, -0.812225]], shape=(1834, 3))

In [49]:
assert v_recon_valve[:len(v_dm_valve)].all() == v_dm_valve.all()

Seems like the vertex structure is the same across the meshes. What about the faces?

In [50]:
f_dm_valve

array([[238, 239, 236],
       [236, 237, 238],
       [241, 238, 237],
       ...,
       [231, 221, 224],
       [224, 232, 231],
       [226, 235, 234]], shape=(3544, 3), dtype=int32)

In [51]:
f_recon_valve

array([[362, 363, 360],
       [360, 361, 362],
       [365, 362, 361],
       ...,
       [340, 356, 355],
       [357, 339, 342],
       [342, 358, 357]], shape=(7088, 3))

Its hard to tell where the face matrix might be differing. For now, let's apply this filter to more meshes and see if its a one-off or consistently being done across the board.

Here, we apply the decimation filter to our steel structure.

In [52]:
ms.clear()

v_recon_steel, f_recon_steel, v_dm_steel, f_dm_steel = decimate_mesh('../../../models/piperack/piperacks_steel_structure.obj')

In [53]:
steel_orig = pymeshlab.Mesh(v_recon_steel, f_recon_steel)
steel_dec = pymeshlab.Mesh(v_dm_steel, f_dm_steel)

ms.add_mesh(steel_orig, "OriginalMesh")
ms.save_current_mesh("steel_reconstruct.obj")

ms.add_mesh(steel_dec, "DecimatedMesh")
ms.save_current_mesh("steel_decimate.obj")

![Steel Structure Preliminary results](../img/steel-decimate-preliminary-results.png)

Seems to be happening here too.

In [54]:
ms.clear()

v_recon_foot_2, f_recon_foot_2, v_dm_foot_2, f_dm_foot_2 = decimate_mesh('../../../models/foot/human-foot.obj')

In [55]:
foot_2_orig = pymeshlab.Mesh(v_recon_foot_2, f_recon_foot_2)
foot_2_dec = pymeshlab.Mesh(v_dm_foot_2, f_dm_foot_2)

ms.add_mesh(foot_2_orig, "OriginalMesh")
ms.save_current_mesh("foot_2_reconstruct.obj")

ms.add_mesh(foot_2_dec, "DecimatedMesh")
ms.save_current_mesh("foot_2_decimate.obj")

This looks successful, so we proceed with converting this to a module. The raw code for this function is saved in the `scripts` folder of this `reducing-mesh-density` subfolder.